apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata: { name: my-entry-service }
spec:
  gateways: [ my-gateway ]
  hosts: [ "*" ]
  http:
  - match:
    - uri: { prefix: / }
    route:
    - destination: { host: sms-app, subset: latest }
      weight: 90
    - destination: { host: sms-app, subset: v1 }
      weight: 10