apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.app.name }}-dr
spec:
  host: {{ .Values.app.name }}
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: {{ .Values.istio.stickyCookieName | default "doda-session" }}
          ttl: {{ .Values.istio.stickyCookieTtl | default "1h" }}
  subsets:
  - name: stable
    labels: { version: stable }
  - name: canary
    labels: { version: canary }
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.model.name }}-dr
spec:
  host: {{ .Values.model.name }}
  subsets:
  - name: stable
    labels: { version: stable }
  - name: canary
    labels: { version: canary }