apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: { name: {{ .Values.app.name }}-dr}
spec:
  host: {{ .Values.app.name }}
  subsets:
  - name: latest
    labels: { version: latest }
  - name: v1
    labels: { version: v1 }
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: { name: {{ .Values.model.name }}-dr}
spec:
  host: {{ .Values.model.name }}
  subsets:
  - name: latest
    labels: { version: latest }
  - name: v1
    labels: { version: v1 }