# Safety check for imbalanced ratios of stable and canary weights.
{{- $stable := .Values.trafficManagement.splitting.stableWeight}}
{{- $canary := .Values.trafficManagement.splitting.canaryWeight}}
{{- $sum := add $stable $canary -}}

{{- if ne $sum 100 -}}
  {{- fail (printf "Traffic Split Invalid / Imbalance: stableWeight + canaryWeight != 100") -}}
{{- end -}}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata: { name: my-entry-service }
spec:
  gateways: [ my-gateway ]
  hosts: [ "*" ]
  http:
  - match:
    - uri: { prefix: / }
    route:
    - destination: { host: {{ .Values.app.name }}, subset: latest }
      weight: {{ .Values.trafficManagement.splitting.stableWeight }}
    - destination: { host: {{ .Values.app.name }}, subset: v1 }
      weight: {{ .Values.trafficManagement.splitting.canaryWeight }}