apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: { name: {{ .Values.app.name }}-dr}
spec:
  host: sms-app
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: { name: {{ .Values.model.name }}-dr}
spec:
  host: sms-model
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary
