apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: { name: sms-app-dr }
spec:
  host: sms-app
  subsets:
  - name: latest
    labels: { version: latest }
  - name: v1
    labels: { version: v1 }
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: { name: sms-model-dr }
spec:
  host: sms-model
  subsets:
  - name: latest
    labels: { version: latest }
  - name: v1
    labels: { version: v1 }