apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.model.name }}-stable
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.model.name }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.model.service.type }}
  selector:
    app: {{ .Values.model.name }}
    release: {{ .Release.Name }}
    version: {{ .Values.model.version | default "stable" }}
  ports:
    - name: http
      port: {{ .Values.model.service.port }}
      targetPort: {{ .Values.model.service.targetPort }}
      protocol: TCP