{
 "title": "SMS Metrics Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active Requests",
   "type": "gauge",
   "description": "Number of requests currently being processed",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_requests", "legendFormat": "Processing" }
   ]
  },
  {
   "title": "Total Requests by Type",
   "type": "bargauge",
   "description": "Total count of Spam, Ham and Failed",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_requests) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Request Rate (Req/sec)",
   "type": "timeseries",
   "description": "Incoming request per second",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "rate(total_requests[1m])", "legendFormat": "{{result}}" }
   ]
  }
 ]
}